baseurl = "/"
title = "Bermylle Razon"
theme = "Blogpaper"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "My description"
    github = "https://github.com/bermylle"
    twitter = "https://twitter.com/bermylle"
    email = "bermylle@gmail.com"
    opengraph = true
    shareTwitter = true


[Permalinks]
    post = "/:filename/"