baseurl = "/"
title = "Bermylle Razon"
theme = "Blogpaper"
language = "en-us"
enableEmoji = "True"

[[menu.main]]
    name = "Home" #Name in the navigation bar
    weight = 10 #The larger the weight, the more on the right this item will be
    url = "/" #URL address

[[menu.main]]
    name = "About"
    weight = 30
    url = "/about/"

[[menu.main]]
    name = "Github"
    weight = 30
    url = "https://github.com/bermylle"

[[menu.main]]
    name = "CV"
    weight = 40
    url = ""