author:
  name: Bermylle Razon
baseURL: https://bermyllerazon.com
languageCode: en
menu:
  main:
    - name: About
      url: /about
params:
  description: Example site for the Hugo's Blogpaper theme
title: Blogpaper
theme: Blogpaper
